/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RolRouteImport } from './routes/rol'
import { Route as PublicacionesRouteImport } from './routes/publicaciones'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as DisenoImagenCorporativaRouteImport } from './routes/diseno-imagen-corporativa'
import { Route as DesarrolloWebEmpresasRouteImport } from './routes/desarrollo-web-empresas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicacionesIndexRouteImport } from './routes/publicaciones.index'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as PublicacionesTreintaMililitrosRouteImport } from './routes/publicaciones.treinta-mililitros'
import { Route as PublicacionesSlugRouteImport } from './routes/publicaciones.$slug'
import { Route as ProyectosKarmaFinancieroRouteImport } from './routes/proyectos.karma-financiero'
import { Route as ProyectosBlindWordsCitizenRouteImport } from './routes/proyectos.blind-words-citizen'
import { Route as ProyectosBlindWordsRouteImport } from './routes/proyectos.blind-words'
import { Route as ProyectosAprendeHistoriaDelArteRouteImport } from './routes/proyectos.aprende-historia-del-arte'

const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RolRoute = RolRouteImport.update({
  id: '/rol',
  path: '/rol',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacionesRoute = PublicacionesRouteImport.update({
  id: '/publicaciones',
  path: '/publicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoImagenCorporativaRoute = DisenoImagenCorporativaRouteImport.update({
  id: '/diseno-imagen-corporativa',
  path: '/diseno-imagen-corporativa',
  getParentRoute: () => rootRouteImport,
} as any)
const DesarrolloWebEmpresasRoute = DesarrolloWebEmpresasRouteImport.update({
  id: '/desarrollo-web-empresas',
  path: '/desarrollo-web-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacionesIndexRoute = PublicacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicacionesRoute,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProyectosRoute,
} as any)
const PublicacionesTreintaMililitrosRoute =
  PublicacionesTreintaMililitrosRouteImport.update({
    id: '/treinta-mililitros',
    path: '/treinta-mililitros',
    getParentRoute: () => PublicacionesRoute,
  } as any)
const PublicacionesSlugRoute = PublicacionesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicacionesRoute,
} as any)
const ProyectosKarmaFinancieroRoute =
  ProyectosKarmaFinancieroRouteImport.update({
    id: '/karma-financiero',
    path: '/karma-financiero',
    getParentRoute: () => ProyectosRoute,
  } as any)
const ProyectosBlindWordsCitizenRoute =
  ProyectosBlindWordsCitizenRouteImport.update({
    id: '/blind-words-citizen',
    path: '/blind-words-citizen',
    getParentRoute: () => ProyectosRoute,
  } as any)
const ProyectosBlindWordsRoute = ProyectosBlindWordsRouteImport.update({
  id: '/blind-words',
  path: '/blind-words',
  getParentRoute: () => ProyectosRoute,
} as any)
const ProyectosAprendeHistoriaDelArteRoute =
  ProyectosAprendeHistoriaDelArteRouteImport.update({
    id: '/aprende-historia-del-arte',
    path: '/aprende-historia-del-arte',
    getParentRoute: () => ProyectosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desarrollo-web-empresas': typeof DesarrolloWebEmpresasRoute
  '/diseno-imagen-corporativa': typeof DisenoImagenCorporativaRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/publicaciones': typeof PublicacionesRouteWithChildren
  '/rol': typeof RolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/proyectos/aprende-historia-del-arte': typeof ProyectosAprendeHistoriaDelArteRoute
  '/proyectos/blind-words': typeof ProyectosBlindWordsRoute
  '/proyectos/blind-words-citizen': typeof ProyectosBlindWordsCitizenRoute
  '/proyectos/karma-financiero': typeof ProyectosKarmaFinancieroRoute
  '/publicaciones/$slug': typeof PublicacionesSlugRoute
  '/publicaciones/treinta-mililitros': typeof PublicacionesTreintaMililitrosRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/publicaciones/': typeof PublicacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desarrollo-web-empresas': typeof DesarrolloWebEmpresasRoute
  '/diseno-imagen-corporativa': typeof DisenoImagenCorporativaRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/rol': typeof RolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/proyectos/aprende-historia-del-arte': typeof ProyectosAprendeHistoriaDelArteRoute
  '/proyectos/blind-words': typeof ProyectosBlindWordsRoute
  '/proyectos/blind-words-citizen': typeof ProyectosBlindWordsCitizenRoute
  '/proyectos/karma-financiero': typeof ProyectosKarmaFinancieroRoute
  '/publicaciones/$slug': typeof PublicacionesSlugRoute
  '/publicaciones/treinta-mililitros': typeof PublicacionesTreintaMililitrosRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/publicaciones': typeof PublicacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desarrollo-web-empresas': typeof DesarrolloWebEmpresasRoute
  '/diseno-imagen-corporativa': typeof DisenoImagenCorporativaRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/publicaciones': typeof PublicacionesRouteWithChildren
  '/rol': typeof RolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/proyectos/aprende-historia-del-arte': typeof ProyectosAprendeHistoriaDelArteRoute
  '/proyectos/blind-words': typeof ProyectosBlindWordsRoute
  '/proyectos/blind-words-citizen': typeof ProyectosBlindWordsCitizenRoute
  '/proyectos/karma-financiero': typeof ProyectosKarmaFinancieroRoute
  '/publicaciones/$slug': typeof PublicacionesSlugRoute
  '/publicaciones/treinta-mililitros': typeof PublicacionesTreintaMililitrosRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/publicaciones/': typeof PublicacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desarrollo-web-empresas'
    | '/diseno-imagen-corporativa'
    | '/legal'
    | '/portfolio'
    | '/proyectos'
    | '/publicaciones'
    | '/rol'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/proyectos/aprende-historia-del-arte'
    | '/proyectos/blind-words'
    | '/proyectos/blind-words-citizen'
    | '/proyectos/karma-financiero'
    | '/publicaciones/$slug'
    | '/publicaciones/treinta-mililitros'
    | '/proyectos/'
    | '/publicaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desarrollo-web-empresas'
    | '/diseno-imagen-corporativa'
    | '/legal'
    | '/portfolio'
    | '/rol'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/proyectos/aprende-historia-del-arte'
    | '/proyectos/blind-words'
    | '/proyectos/blind-words-citizen'
    | '/proyectos/karma-financiero'
    | '/publicaciones/$slug'
    | '/publicaciones/treinta-mililitros'
    | '/proyectos'
    | '/publicaciones'
  id:
    | '__root__'
    | '/'
    | '/desarrollo-web-empresas'
    | '/diseno-imagen-corporativa'
    | '/legal'
    | '/portfolio'
    | '/proyectos'
    | '/publicaciones'
    | '/rol'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/proyectos/aprende-historia-del-arte'
    | '/proyectos/blind-words'
    | '/proyectos/blind-words-citizen'
    | '/proyectos/karma-financiero'
    | '/publicaciones/$slug'
    | '/publicaciones/treinta-mililitros'
    | '/proyectos/'
    | '/publicaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesarrolloWebEmpresasRoute: typeof DesarrolloWebEmpresasRoute
  DisenoImagenCorporativaRoute: typeof DisenoImagenCorporativaRoute
  LegalRoute: typeof LegalRoute
  PortfolioRoute: typeof PortfolioRoute
  ProyectosRoute: typeof ProyectosRouteWithChildren
  PublicacionesRoute: typeof PublicacionesRouteWithChildren
  RolRoute: typeof RolRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rol': {
      id: '/rol'
      path: '/rol'
      fullPath: '/rol'
      preLoaderRoute: typeof RolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicaciones': {
      id: '/publicaciones'
      path: '/publicaciones'
      fullPath: '/publicaciones'
      preLoaderRoute: typeof PublicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-imagen-corporativa': {
      id: '/diseno-imagen-corporativa'
      path: '/diseno-imagen-corporativa'
      fullPath: '/diseno-imagen-corporativa'
      preLoaderRoute: typeof DisenoImagenCorporativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desarrollo-web-empresas': {
      id: '/desarrollo-web-empresas'
      path: '/desarrollo-web-empresas'
      fullPath: '/desarrollo-web-empresas'
      preLoaderRoute: typeof DesarrolloWebEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicaciones/': {
      id: '/publicaciones/'
      path: '/'
      fullPath: '/publicaciones/'
      preLoaderRoute: typeof PublicacionesIndexRouteImport
      parentRoute: typeof PublicacionesRoute
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/publicaciones/treinta-mililitros': {
      id: '/publicaciones/treinta-mililitros'
      path: '/treinta-mililitros'
      fullPath: '/publicaciones/treinta-mililitros'
      preLoaderRoute: typeof PublicacionesTreintaMililitrosRouteImport
      parentRoute: typeof PublicacionesRoute
    }
    '/publicaciones/$slug': {
      id: '/publicaciones/$slug'
      path: '/$slug'
      fullPath: '/publicaciones/$slug'
      preLoaderRoute: typeof PublicacionesSlugRouteImport
      parentRoute: typeof PublicacionesRoute
    }
    '/proyectos/karma-financiero': {
      id: '/proyectos/karma-financiero'
      path: '/karma-financiero'
      fullPath: '/proyectos/karma-financiero'
      preLoaderRoute: typeof ProyectosKarmaFinancieroRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/proyectos/blind-words-citizen': {
      id: '/proyectos/blind-words-citizen'
      path: '/blind-words-citizen'
      fullPath: '/proyectos/blind-words-citizen'
      preLoaderRoute: typeof ProyectosBlindWordsCitizenRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/proyectos/blind-words': {
      id: '/proyectos/blind-words'
      path: '/blind-words'
      fullPath: '/proyectos/blind-words'
      preLoaderRoute: typeof ProyectosBlindWordsRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/proyectos/aprende-historia-del-arte': {
      id: '/proyectos/aprende-historia-del-arte'
      path: '/aprende-historia-del-arte'
      fullPath: '/proyectos/aprende-historia-del-arte'
      preLoaderRoute: typeof ProyectosAprendeHistoriaDelArteRouteImport
      parentRoute: typeof ProyectosRoute
    }
  }
}

interface ProyectosRouteChildren {
  ProyectosAprendeHistoriaDelArteRoute: typeof ProyectosAprendeHistoriaDelArteRoute
  ProyectosBlindWordsRoute: typeof ProyectosBlindWordsRoute
  ProyectosBlindWordsCitizenRoute: typeof ProyectosBlindWordsCitizenRoute
  ProyectosKarmaFinancieroRoute: typeof ProyectosKarmaFinancieroRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

const ProyectosRouteChildren: ProyectosRouteChildren = {
  ProyectosAprendeHistoriaDelArteRoute: ProyectosAprendeHistoriaDelArteRoute,
  ProyectosBlindWordsRoute: ProyectosBlindWordsRoute,
  ProyectosBlindWordsCitizenRoute: ProyectosBlindWordsCitizenRoute,
  ProyectosKarmaFinancieroRoute: ProyectosKarmaFinancieroRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
}

const ProyectosRouteWithChildren = ProyectosRoute._addFileChildren(
  ProyectosRouteChildren,
)

interface PublicacionesRouteChildren {
  PublicacionesSlugRoute: typeof PublicacionesSlugRoute
  PublicacionesTreintaMililitrosRoute: typeof PublicacionesTreintaMililitrosRoute
  PublicacionesIndexRoute: typeof PublicacionesIndexRoute
}

const PublicacionesRouteChildren: PublicacionesRouteChildren = {
  PublicacionesSlugRoute: PublicacionesSlugRoute,
  PublicacionesTreintaMililitrosRoute: PublicacionesTreintaMililitrosRoute,
  PublicacionesIndexRoute: PublicacionesIndexRoute,
}

const PublicacionesRouteWithChildren = PublicacionesRoute._addFileChildren(
  PublicacionesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesarrolloWebEmpresasRoute: DesarrolloWebEmpresasRoute,
  DisenoImagenCorporativaRoute: DisenoImagenCorporativaRoute,
  LegalRoute: LegalRoute,
  PortfolioRoute: PortfolioRoute,
  ProyectosRoute: ProyectosRouteWithChildren,
  PublicacionesRoute: PublicacionesRouteWithChildren,
  RolRoute: RolRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
